config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_names => { :sign_up => "register/orizon/blockchain/sign_up" }
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :client do
    resources :treatments, only: [:new, :create, :index, :edit, :update, :destroy, :show]
  end

  resources :users, only: [:new, :create, :index, :edit, :update, :destroy, :show] do
    resources :treatments, only: :index

  end

  # resources :treatments, only: :index

  get "/question" => "pages#show", :as => '/question'

  get "client/faq" => "users#faq", :as => 'client/faq'

  # post 'create_user' => 'users#create', as: :create_user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/town.rb
class Town < ApplicationRecord
  # belongs_to :user
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :client, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
   self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :treatments
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def manage_users
  end

  def edit_user_details
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_sign_up_role, if: :devise_controller?



  def set_sign_up_role
    session[:role] = params[:as] if params[:as]
  end

  def after_sign_in_path_for(resource)
    if resource.user?
      client_treatments_path
    elsif resource.client?
      client_treatments_path
    elsif resource.admin?
      users_path
    end
  end

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/client/treatments_controller.rb
class Client::TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

   def index
     @treatments = current_user.treatments
  end

   def show
   end

   def new
     @treatment = Treatment.new
     # @town = current_user.town || Town.new
   end

   def create
     @treatment = Treatment.new(treatment_params)
     @treatment.user = current_user
     if @treatment.save
       redirect_to client_treatments_path(@treatment)
     else
       render :new
     end
   end

   def edit
   end

   def update
     @treatment.update(treatment_params)
     if @treatment.save
       redirect_to client_treatments_path(@treatment)
     else
       render :edit
     end
   end

   def destroy
     @treatment.destroy
     redirect_to client_treatments_path
   end

   private

   def set_treatment
     @treatment = Treatment.find(params[:id])
   end

   def treatment_params
     params.require(:treatment).permit(:user_id, :name, :start_date, :main_purpose, :other_purpose, :service_concerned, :service_function, :category_people_concerned, :personal_data, :sensitive_data, :recipient, :storage_time, :observation)
   end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :show]

  layout 'public'
  def home
  end

  def show
    render template: "pages/question"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:create]
  before_action :admin_only, :except => [:show, :faq]
  # before_filter :authorize_admin, :only => :create
  prepend_before_filter :require_no_authentication, only: [:cancel]


  def index
    @users = User.all
  end

  def new
    @user = User.new
    # @town = current_user.town || Town.new
  end

  def create
    @user = User.new(user_params)
    # @user.user = current_user

    if @user.save
      redirect_to users_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(secure_params)
  #     redirect_to users_path, :notice => "User updated."
  #   else
  #     redirect_to users_path, :alert => "Unable to update user."
  #   end
  # end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to users_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def faq
    render template: "client/faq"
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

  def user_params
    params.require(:user).permit(:first_name)
  end

  # def authorize_admin
  #   return unless !current_user.admin?
  #   redirect_to root_path, alert: 'Admins only!'
  # end

  def authorize_admin
    redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/client/treatments/edit.html.erb
<div class="container">
  <h4 class="text-center page-title">Modifier le traitement de données</h4>
  <%= render 'form' %>
</div>

app/views/client/treatments/index.html.erb
<div class="treatments">
  <div class="treatments-title">
    <div class="treatments-title-help">
      <h1>Mes traitements de données personnelles</h1>
      <div class="help-tip">
        <p><u>Traitement de données personnelles :</u> toute opération, ou ensemble d’opérations, portant sur des données permettant d'identifier un individu, quel que soit le procédé utilisé (collecte, enregistrement, organisation, conservation, adaptation, modification, extraction, consultation, utilisation, communication par transmission diffusion ou toute autre forme de mise à disposition, rapprochement ou interconnexion, verrouillage, effacement ou destruction, ...). <b>Vous devez indiquer tous les traitements de votre structure qu'ils soient numériques ou papiers.</b></p>
      </div>
    </div>
    <%= link_to "Ajouter un traitement", new_client_treatment_path, class: "btn-add-treatment" %>
    <%#= link_to 'Download CSV list', treatments_path(format: :csv) %>
  </div>

  <div class="treatments-content">
    <div class="treatments-header">
      <div class="col5 col-sm-6">
        <p>Nom du traitement</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Date de démarrage</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Finalité principale</p>
      </div>
      <div class="col5 col-sm-6">
        <p>Service concerné</p>
      </div>
      <div class="col5 col-sm-6">
        <p> </p>
      </div>
    </div>

    <% @treatments.each do |treatment| %>
    <!-- <div class="list-treatment"> -->
      <%#= link_to client_treatment_path(treatment) do %>
        <div class="treatment">
          <div class="col5 col-sm-6">
            <p><%= treatment.name %></p>
          </div>
          <div class="col5 col-sm-6">
            <p><%= treatment.start_date %></p>
          </div>
          <div class="col5 col-sm-6">
            <p><%= treatment.main_purpose %></p>
          </div>
          <div class="col5 col-sm-6">
            <p><%= treatment.service_concerned %></p>
          </div>
          <div class="col5 col-sm-6">
            <%= link_to "Voir", client_treatment_path(treatment), class: "btn-treatment" %>
          </div>
        </div>
        <%# end %>
      <!-- </div> -->
    <% end %>
  </div>

</div>

app/views/client/treatments/new.html.erb
<div class="container">
  <h4 class="text-center page-title">Nouveau traitement de données personnelles</h4>
  <%= render 'form' %>
</div>

app/views/client/treatments/show.html.erb
<div class="treatment-show">
  <div class="col-lg-12">
    <div class="treatment-show-header">
      <div class="treatment-show-return">
        <%= link_to client_treatments_path do %>
          <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="treatment-show-header-text">
        <h1>Informations</h1>
      </div>
    </div>

    <div class="treatment-show-content">
      <div class="treatment-item">
        <div class="treatment-label">
          Nom du traitement :
        </div>
        <div class="treatment-content">
          <%= @treatment.name %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Date de démarrage :
        </div>
        <div class="treatment-content">
          <%= @treatment.start_date %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Objectif principal :
        </div>
        <div class="treatment-content">
          <%= @treatment.main_purpose %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Autres objectifs :
        </div>
        <div class="treatment-content">
          <%= @treatment.other_purpose %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Service concerné :
        </div>
        <div class="treatment-content">
          <%= @treatment.service_concerned %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Fonction du service :
        </div>
        <div class="treatment-content">
          <%= @treatment.service_function %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Catégories de personnes concernées :
        </div>
        <div class="treatment-content">
          <%= @treatment.category_people_concerned %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Données personnelles récoltées :
        </div>
        <div class="treatment-content">
          <%= @treatment.category_people_concerned %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Données personnelles sensibles :
        </div>
        <div class="treatment-content">
          <%= @treatment.sensitive_data %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Destinataire :
        </div>
        <div class="treatment-content">
          <%= @treatment.recipient %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Temps de conservation des données :
        </div>
        <div class="treatment-content">
          <%= @treatment.storage_time %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Observations :
        </div>
        <div class="treatment-content">
          <%= @treatment.observation %>
        </div>
      </div>
    </div>

    <div class="btns-treatment">
      <% if current_user == @treatment.user %>
        <div class="edit">
          <%= link_to "EDITER", edit_client_treatment_path(@treatment), class: "btn-edit" %>
        </div>
        <div class="delete">
          <%= link_to "SUPPRIMER", client_treatment_path(@treatment), method: :delete, class: "btn-delete" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Horizon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body class="application">
    <% unless devise_controller? %>
      <%= render "shared/sidebar" %>
    <% end %>
    <div class="content">
      <% if current_user.present? %>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <% end %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="large-header" class="large-header spirale">
  <canvas id="demo-canvas"></canvas>
    <h1 class="main-title">
      <span class="thin">HORIZON</span>
      <p class="subtitle">La conformité de vos données n'a jamais été aussi simple</p>
    </h1>
</div>


<!-- Banner présentation de la réglementation -->
<div class="container first-step-content city-orizon">
  <div class="col-md-12 content-center">
    <h1>VOS OBLIGATIONS EN MATIÈRE DE DONNÉES PERSONNELLES ÉVOLUENT. NOUS SOMMES LÀ POUR VOUS AIDER ET VOUS ACCOMPAGNER.</h1>
    <div class="text-1">
      <h3>Le règlement général sur la protection des données personnelles prévoit des sanctions très sévères en cas de manquement à ses prescriptions, pouvant aller jusqu’à 4 millions d’euros ou 20% du chiffre d’affaire annuel.</h3>
    </div>
    <div class="text-2">
      <h3>Horizon propose aux structures publiques (collectivités, établissements publics, associations…) et privées (TPE, ETI, PME…) une solution SaaS inédite de cartographie et de traitement des données personnelles en parfaite conformité au cadre défini par la réglementation européenne.</h3>
    </div>
    <div class="btn-contact">
      <%= link_to "FAIRE LE TEST DE CONFORMITÉ", question_path, class: "btn-blue" %>
    </div>
  </div>
</div>

<!-- Banner notre solution -->
<div class="container second-step-content">
  <div class="col-md-12">
    <h1>NOTRE SOLUTION</h1>
    <div class="mini-feature col-md-4">
      <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
      <h3 class="mini-feature-heading">Structurez vos données</h3>
      <p class="mini-feature-description">Maîtrisez vos données grâce à une cartographie intégrale de vos traitements de données personnelles.
      </p>
    </div>
    <div class="mini-feature col-md-4">
      <img alt="Apps" src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/conformite_j9s2lg.png">
      <h3 class="mini-feature-heading">Avancez en toute conformité</h3>
      <p class="mini-feature-description">Faites le choix de la conformité et reprenez le contrôle sur vos données personnelles.
      </p>
    </div>
    <div class="mini-feature col-md-4">
      <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/protegee_g1abdp.png">
      <h3 class="mini-feature-heading">Protégez vos activités</h3>
      <p class="mini-feature-description">Visualisez et gérez vos traitements de données personnelles en toute sécurité.
      </p>
    </div>
  </div>
</div>

<!-- Banner de l'accompagnement vers la conformité -->
<div class="container third-step-content">
  <div class="col-md-12">
    <h1>UN ACCOMPAGNEMENT VERS LA CONFORMITÉ</h1>
    <div class="col-md-2">
    </div>
    <div class="col-md-8 icon-vert">
      <div class="row">
        <div class="col-md-2 icon-vert-img">
          <img alt="Apps" src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_30/v1517399016/success_xfy0lo.png">
        </div>
        <div class="col-md-10 icon-vert-text">
          <p>Désignez Horizon comme délégué à la protection des données</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 icon-vert-img">
          <img alt="Apps" src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_30/v1517399016/success_xfy0lo.png">
        </div>
        <div class="col-md-10 icon-vert-text">
          <p>Bénéficiez d'un accompagnement personnalisé</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 icon-vert-img">
          <img alt="Apps" src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_30/v1517399016/success_xfy0lo.png">
        </div>
        <div class="col-md-10 icon-vert-text">
          <p>Bénéficiez de conseils sur vos obligations</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 icon-vert-img">
          <img alt="Apps" src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_30/v1517399016/success_xfy0lo.png">
        </div>
        <div class="col-md-10 icon-vert-text">
          <p>Bénéficiez de conseils sur la réalisation d'études d'impact</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 icon-vert-img">
          <img alt="Apps" src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_30/v1517399016/success_xfy0lo.png">
        </div>
        <div class="col-md-10 icon-vert-text">
          <p>Horizon est votre interlocuteur pour l'autorité de contrôle nationale</p>
        </div>
      </div>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

<!-- Banner présentation de la plateforme -->
<div class="container third-step-content-white">
  <div class="col-md-12">
    <h1>NOTRE PLATEFORME</h1>
    <div class="banner-plateforme-feature">
      <div class="col-md-6 banner-plateforme-feature-text">
        <div class="row">
          <div class="col-md-6 feature">
            <div class="feature-header">
              <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
              <h1>Sécurisée</h1>
            </div>
            <p>Aucun risque de piratage grâce à la technologie blockchain.</p>
          </div>
          <div class="col-md-6 feature">
            <div class="feature-header">
              <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
              <h1>Sur-mesure</h1>
            </div>
            <p>Une plaforme adaptée à vos besoins à travers une interface personnalisée.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 feature">
            <div class="feature-header">
              <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
              <h1>Facile</h1>
            </div>
            <p>Laissez-vous guider par une prise en main simplifiée.</p>
          </div>
          <div class="col-md-6 feature">
            <div class="feature-header">
              <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513337439/data-protection_rcxefl.png">
              <h1>Connectée</h1>
            </div>
            <p>Accédez à votre compte n’importe où depuis votre ordinateur, votre téléphone ou votre tablette.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="banner-plateforme-feature-photo hidden-xs">
          <img src="https://res.cloudinary.com/ddjlhkips/image/upload/v1513419879/Macbook-orizon_bhecxr.png">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Banner de liens utiles -->
<div class="container third-step-content">
  <div class="col-md-12">
    <h1>LIENS UTILES</h1>
    <div class="liens-utiles">
      <div class="col-md-3 logo-links">
        <a href="https://www.gdpr-expert.eu" target="_blank">
          <img src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_150/v1517404928/te%CC%81le%CC%81chargement_ooqtyx.png">
        </a>
      </div>
      <div class="col-md-3 logo-links">
        <a href="http://www.afcdp.net/" target="_blank">
          <img src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_150/v1517404941/afcdp_e6oujr.png">
        </a>
      </div>
      <div class="col-md-3 logo-links">
        <a href="https://www.cnil.fr" target="_blank">
          <img src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_150/v1517404929/logo_cnil_rcjnb3.png">
        </a>
      </div>
      <div class="col-md-3 logo-links">
        <a href="https://ec.europa.eu/commission/index_fr" target="_blank">
          <img src="http://res.cloudinary.com/ddjlhkips/image/upload/c_scale,w_135/v1517404928/Logo_Commission_Europe%CC%81enne_FR_l8o2dl.png">
        </a>
      </div>
    </div>
  </div>
</div>

<!-- Banner Contact -->
<div id="nous-contacter" class="container fourth-step-content">
  <div class="col-md-12">
    <h1>NOUS CONTACTER</h1>

    <div class="container">
      <div class="simple-form">
        <form action="https://getsimpleform.com/messages?form_api_token=8e394b20a9f5ac1cf59a9b4e4ad2255b" method="post">
          <!-- the redirect_to is optional, the form will redirect to the referrer on submission -->
          <!-- <input type='hidden' name='redirect_to' value='http://localhost:3000' /> -->
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <input type='name' name='Nom' class='input-form first-form' placeholder="Nom" />
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <input type='name' name='Prénom' class='input-form first-form' placeholder="Prénom" />
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <input type='email' name='email' class='input-form' placeholder="Email"/>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <input type='name' name='Téléphone' class='input-form' placeholder="Téléphone" />
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <input type='name' name='Structure' class='input-form' placeholder="Structure" />
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <input type='description' name='message' class='input-message' placeholder="Votre message">
          </div>
          <div class="col-xs-12 col-sm-4 col-sm-offset-4 btn-contact-form">
          <input type='submit' value='ENVOYER' class="btn-contact" onclick="myFunction()" />
          </div>
        </form>
      </div>
    </div>

  </div>
</div>

<script>
function myFunction() {
    alert("Votre message a bien été envoyé. Nous revenons vers vous très vite.");
}
</script>

<!-- Footer -->
<div class="footer">
    <div class="container">
      <div class="footer-copyright">
        <h4>© 2017 Horizon Technologies. Tous droits réservés.</h4>
      </div>
    </div>
  <!-- <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div> -->

</div>

app/views/shared/_navbar-home.html.erb
<div class="navbar-orizon-home">

  <div class="navbar-orizon-home-brand">
    <% if current_page?(question_path) %>
      <%= link_to root_path do %>
         <%= image_tag "logo.png", class: "navbar-orizon-home-brand" %>
      <% end %>
    <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-orizon-home-right hidden-xs hidden-sm">
    <%= link_to "Nous contacter", root_path(:anchor => "nous-contacter"), class: "navbar-orizon-home-item navbar-orizon-home-link" %>
    <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-orizon-home-item navbar-orizon-home-link-connexion" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-orizon-home-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-orizon-home-dropdown-menu">
        <%= link_to "Nous contacter", root_path(:anchor => "nous-contacter") %>
        <li><a href="#">Connexion</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar_color">
    <h2>HORIZON</h2>
  </div>

  <div class="container_menu side_menu pullRight">
    <% if current_user.admin? %>
    <%= link_to "Dashboard", users_path %>
    <%= link_to "Nouveau Client", new_user_session_path %>
    <% end %>
    <%= link_to "Traitements", client_treatments_path %>
    <%#= link_to "Ajouter un traitement", new_client_treatment_path %>
    <%= link_to "Questions", client_faq_path %>
      <a href="#">Projets en cours</a>

      <a href="#">Déconnexion</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="dashboard">
    <div class="row">
      <div class="data-dashboard">
        <div class="individual-data">
          <div class="individual-data-data">
            <%= @users.count if @users.count %>
          </div>
          <div class="individual-data-title">
            Clients
          </div>
        </div>
        <div class="individual-data">
          <div class="individual-data-data">
            <%= Treatment.count %>
          </div>
          <div class="individual-data-title">
            Traitements
          </div>
        </div>
        <div class="individual-data">
          <div class="individual-data-data">
            0
          </div>
          <div class="individual-data-title">
            Statistiques
          </div>
        </div>
        <div class="individual-data">
          <div class="individual-data-data">
            0
          </div>
          <div class="individual-data-title">
            Documents
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <!-- <h3>Clients</h3> -->
      <div class="clients-list">
        <div class="clients-list-title">
          <h1>Clients</h1>
          <%= link_to "Nouveau client", new_user_path, class: "btn-add-treatment" %>
        </div>
        <div class="column">
          <table class="table">
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <%= render user %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="treatment-show">
  <div class="col-lg-12">
    <div class="treatment-show-header">
      <div class="treatment-show-return">
        <%= link_to users_path do %>
          <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="treatment-show-header-text">
        <h1>Informations</h1>
      </div>
    </div>

    <div class="treatment-show-content">
      <div class="treatment-item">
        <div class="treatment-label">
          Commune :
        </div>
        <div class="treatment-content">
          <%= @user.town_name if @user.town_name %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Nom du maire :
        </div>
        <div class="treatment-content">
          <%= @user.last_name if @user.last_name %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Prénom du maire :
        </div>
        <div class="treatment-content">
          <%= @user.first_name if @user.first_name %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Numéro de téléphone :
        </div>
        <div class="treatment-content">
          <%= @user.phone_number if @user.phone_number %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Email :
        </div>
        <div class="treatment-content">
          <%= @user.email if @user.email %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Client créé le :
        </div>
        <div class="treatment-content">
          <%= @user.created_at if @user.created_at %>
        </div>
      </div>
      <div class="treatment-item">
        <div class="treatment-label">
          Date de la dernière modification :
        </div>
        <div class="treatment-content">
          <%= @user.created_at if @user.created_at %>
        </div>
      </div>
    </div>

    <div class="btns-treatment">
      <%= link_to "Modifier la fiche client", edit_user_path(@user), class: "btn-edit" %>
      <%= link_to("Supprimer le client", user_path(@user), :data => { :confirm => "Êtes-vous sûr de vouloir supprimer cet utilisateur ?" }, :method => :delete, :class => 'btn-delete') unless @user == current_user %>
      <% unless @user.admin? %>
        <%= form_for(@user) do |f| %>
        <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
        <%= f.submit 'Changer le rôle', :class => 'button-xs' %>
        <% end %>
      <% end %>

    </div>

  </div>
</div>